"""Add invoice image_url

Revision ID: 032165b297d7
Revises: 406d036f6f16
Create Date: 2026-02-08 16:44:51.947665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032165b297d7'
down_revision = '406d036f6f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
