"""add pos discount tracking fields

Revision ID: 04165db709a4
Revises: ead6cb238261
Create Date: 2026-06-06 12:02:40.334654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04165db709a4'
down_revision = 'ead6cb238261'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'subtotal_before_discount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        ))
        batch_op.add_column(sa.Column(
            'discount_type',
            sa.String(length=20),
            nullable=False,
            server_default='none'
        ))
        batch_op.add_column(sa.Column(
            'discount_amount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        ))
        batch_op.add_column(sa.Column(
            'discount_total',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        ))

    with op.batch_alter_table('pos_closeouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'expected_discount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_closeouts', schema=None) as batch_op:
        batch_op.drop_column('expected_discount')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('discount_total')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('subtotal_before_discount')

    # ### end Alembic commands ###
