"""add api token to users

Revision ID: 121032c1d0e4
Revises: 71d30ced8fe4
Create Date: 2026-03-16 22:10:29.961937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121032c1d0e4'
down_revision = '71d30ced8fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_token'))
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
