"""add shipment receiving scan logs

Revision ID: 25fa57f9f2de
Revises: 9b7e10d43504
Create Date: 2026-05-29 12:22:50.632430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fa57f9f2de'
down_revision = '9b7e10d43504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shipment_scan_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shipment_id', sa.Integer(), nullable=False),
        sa.Column('package_id', sa.Integer(), nullable=True),
        sa.Column('scanned_value', sa.String(length=255), nullable=False),
        sa.Column('scan_result', sa.String(length=30), nullable=False),
        sa.Column('scanned_by_id', sa.Integer(), nullable=True),
        sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('notes', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
        sa.ForeignKeyConstraint(['scanned_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['shipment_id'], ['shipment_log.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('shipment_scan_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_scan_logs_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_scan_logs_scanned_by_id'), ['scanned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_scan_logs_scanned_value'), ['scanned_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_scan_logs_shipment_id'), ['shipment_id'], unique=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'received_scan_status',
            sa.String(length=30),
            nullable=False,
            server_default='not_scanned'
        ))
        batch_op.add_column(sa.Column('received_scanned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('received_scanned_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_packages_received_scan_status'), ['received_scan_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_received_scanned_by_id'), ['received_scanned_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['received_scanned_by_id'], ['id'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('received_scan_status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_packages_received_scanned_by_id'))
        batch_op.drop_index(batch_op.f('ix_packages_received_scan_status'))
        batch_op.drop_column('received_scanned_by_id')
        batch_op.drop_column('received_scanned_at')
        batch_op.drop_column('received_scan_status')

    with op.batch_alter_table('shipment_scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_scan_logs_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_scan_logs_scanned_value'))
        batch_op.drop_index(batch_op.f('ix_shipment_scan_logs_scanned_by_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_scan_logs_package_id'))

    op.drop_table('shipment_scan_logs')
    # ### end Alembic commands ###