"""add employee code to users

Revision ID: 2bfcac87c55e
Revises: d08725f5cd94
Create Date: 2026-04-25 09:08:17.877169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfcac87c55e'
down_revision = 'd08725f5cd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_employee_code'), ['employee_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_code'))
        batch_op.drop_column('employee_code')

    # ### end Alembic commands ###
