"""Add delivery invoice fields to scheduled_deliveries

Revision ID: 2dfa79ef7e0d
Revises: e66cadf014c2
Create Date: 2026-02-23 19:51:37.946622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfa79ef7e0d'
down_revision = 'e66cadf014c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=40), nullable=True))

        # ✅ add NOT NULL fields with SERVER DEFAULTS so existing rows don't break
        batch_op.add_column(
            sa.Column(
                'delivery_fee',
                sa.Numeric(precision=10, scale=2),
                nullable=False,
                server_default=sa.text("1000.00")
            )
        )
        batch_op.add_column(
            sa.Column(
                'fee_currency',
                sa.String(length=10),
                nullable=False,
                server_default=sa.text("'JMD'")
            )
        )
        batch_op.add_column(
            sa.Column(
                'fee_status',
                sa.String(length=20),
                nullable=False,
                server_default=sa.text("'Unpaid'")
            )
        )

        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_scheduled_deliveries_invoice_number'),
            ['invoice_number'],
            unique=True
        )

    # ✅ OPTIONAL: remove server defaults after the migration runs successfully
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.alter_column('delivery_fee', server_default=None)
        batch_op.alter_column('fee_currency', server_default=None)
        batch_op.alter_column('fee_status', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_invoice_number'))
        batch_op.drop_column('paid_at')
        batch_op.drop_column('fee_status')
        batch_op.drop_column('fee_currency')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
