"""add claims and claim audit logs

Revision ID: 2e9792c86907
Revises: 4730019fd9cd
Create Date: 2026-03-02 22:55:23.048097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9792c86907'
down_revision = '4730019fd9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_awb', sa.String(length=64), nullable=False),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('item_value_jmd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=False),
    sa.Column('invoice_public_id', sa.String(length=255), nullable=True),
    sa.Column('bank_statement_url', sa.Text(), nullable=False),
    sa.Column('bank_statement_public_id', sa.String(length=255), nullable=True),
    sa.Column('refund_method', sa.String(length=20), nullable=False),
    sa.Column('bank_account_name', sa.String(length=120), nullable=True),
    sa.Column('bank_branch', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=60), nullable=True),
    sa.Column('bank_account_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_amount_jmd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_house_awb'), ['house_awb'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_reviewed_by_admin_id'), ['reviewed_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_tracking_number'), ['tracking_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_user_id'), ['user_id'], unique=False)

    op.create_table('claim_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_audit_logs_actor_admin_id'), ['actor_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_audit_logs_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_audit_logs_claim_id'))
        batch_op.drop_index(batch_op.f('ix_claim_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_claim_audit_logs_actor_admin_id'))

    op.drop_table('claim_audit_logs')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_claims_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_reviewed_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_claims_house_awb'))

    op.drop_table('claims')
    # ### end Alembic commands ###
