"""Add pricing_locked to package

Revision ID: 31026b82d5d1
Revises: bdd7e2361594
Create Date: 2026-02-12 11:33:01.614602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31026b82d5d1'
down_revision = 'bdd7e2361594'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'pricing_locked',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')  # or sa.false()
        ))
        batch_op.add_column(sa.Column('pricing_locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pricing_locked_by', sa.Integer(), nullable=True))

    # optional cleanup
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('pricing_locked', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('pricing_locked_by')
        batch_op.drop_column('pricing_locked_at')
        batch_op.drop_column('pricing_locked')

    # ### end Alembic commands ###
