"""add subscription invites

Revision ID: 334fa608c9a5
Revises: 71b464018344
Create Date: 2026-05-03 19:34:32.525637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334fa608c9a5'
down_revision = '71b464018344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_invites_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_invites_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_invites_token'))
        batch_op.drop_index(batch_op.f('ix_subscription_invites_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_invites_email'))

    op.drop_table('subscription_invites')
    # ### end Alembic commands ###
