"""expense attachments cloudinary

Revision ID: 34a9f785f29b
Revises: 567cda9ca6cc
Create Date: 2026-02-11 14:33:52.637476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a9f785f29b'
down_revision = '567cda9ca6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_public_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('attachment_stored')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_stored', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('attachment_public_id')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###
