"""fix logistics models

Revision ID: 358365bdf36a
Revises: a8b23e3cc1fa
Create Date: 2025-11-21 12:58:20.310236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358365bdf36a'
down_revision = 'f7aab9ba8be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('received_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('customer_id')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('house_number')
        batch_op.drop_column('manifest_date')

    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_users_referral_code",   # name of the constraint
            ['referral_code']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_users_referral_code",
            type_='unique'
        )

    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manifest_date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('house_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('received_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
