"""add area_zone to scheduled_deliveries

Revision ID: 39ce3eb541e4
Revises: cb229572eb0c
Create Date: 2026-03-01 18:54:56.587704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ce3eb541e4'
down_revision = 'cb229572eb0c'
branch_labels = None
depends_on = None


def upgrade():
    # 1) add column as NULLABLE first (so existing rows don't break)
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_zone', sa.String(length=30), nullable=True))

    # 2) backfill old rows with a safe default
    # choose whatever default makes sense for "unknown/old" deliveries
    op.execute("UPDATE scheduled_deliveries SET area_zone = 'kgn_core' WHERE area_zone IS NULL")

    # 3) now enforce NOT NULL
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.alter_column(
            'area_zone',
            existing_type=sa.String(length=30),
            nullable=False
        )

        # 4) create the index after the data is non-null (safe either way)
        batch_op.create_index(
            batch_op.f('ix_scheduled_deliveries_area_zone'),
            ['area_zone'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_area_zone'))
        batch_op.drop_column('area_zone')

    # ### end Alembic commands ###
