"""add bad address fee to settings

Revision ID: 3a830906b06a
Revises: f30ee4ebe1d6
Create Date: 2026-03-08 20:11:19.923206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a830906b06a'
down_revision = 'f30ee4ebe1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bad_address_fee_jmd', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('bad_address_fee_jmd')

    # ### end Alembic commands ###
