"""add delivery reschedule fields

Revision ID: 3a9111600383
Revises: ffc62e2dc629
Create Date: 2026-05-21 01:36:00.827905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9111600383'
down_revision = 'ffc62e2dc629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reschedule_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('requested_new_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_column('reschedule_status')
        batch_op.drop_column('reschedule_reason')
        batch_op.drop_column('requested_new_date')
        batch_op.drop_column('reschedule_requested_at')
        batch_op.drop_column('reschedule_requested')

    # ### end Alembic commands ###
