"""Add message threads and archive/delete flags

Revision ID: 3e9a6ea45a26
Revises: 98d0577ffc95
Create Date: 2026-01-07 23:38:20.240521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9a6ea45a26'
down_revision = '98d0577ffc95'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_key', sa.String(length=64), nullable=True))

        # ✅ add booleans with a SERVER default so existing rows get a value
        batch_op.add_column(sa.Column('archived_by_sender', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('archived_by_recipient', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('deleted_by_recipient', sa.Boolean(), nullable=False, server_default=sa.text('false')))

        batch_op.create_index('ix_messages_thread_key', ['thread_key'], unique=False)

    # ✅ optional but recommended: remove server defaults after backfill
    # (keeps schema clean; your model defaults still apply at ORM level)
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('archived_by_sender', server_default=None)
        batch_op.alter_column('archived_by_recipient', server_default=None)
        batch_op.alter_column('deleted_by_sender', server_default=None)
        batch_op.alter_column('deleted_by_recipient', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_key'))
        batch_op.drop_column('deleted_by_recipient')
        batch_op.drop_column('deleted_by_sender')
        batch_op.drop_column('archived_by_recipient')
        batch_op.drop_column('archived_by_sender')
        batch_op.drop_column('thread_key')

    # ### end Alembic commands ###
