"""add payroll position title

Revision ID: 3ec6a087d97e
Revises: 47e5787f0f23
Create Date: 2026-06-08 20:15:30.426186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec6a087d97e'
down_revision = '47e5787f0f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_title', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_payroll_position_title'), ['position_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_payroll_position_title'))
        batch_op.drop_column('position_title')

    # ### end Alembic commands ###
