"""add last_login to users

Revision ID: 406d036f6f16
Revises: d6acecdfd804
Create Date: 2026-01-09 21:41:44.219113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406d036f6f16'
down_revision = 'd6acecdfd804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
