"""init clean

Revision ID: 43835e63f192
Revises: 
Create Date: 2025-11-03 14:13:34.603945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43835e63f192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counters')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('freight_fee')
        batch_op.drop_column('stamp')
        batch_op.drop_column('grand_total')
        batch_op.drop_column('freight_total')
        batch_op.drop_column('customs_total')
        batch_op.drop_column('storage_fee')
        batch_op.drop_column('other_charges')

    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shipment_log_slid'))

    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_shipment_packages_package'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_shipment_packages_package'), ['package_id'], unique=1)

    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_shipment_log_slid'), ['sl_id'], unique=1)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_charges', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('storage_fee', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('customs_total', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('freight_total', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('grand_total', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('stamp', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('freight_fee', sa.REAL(), server_default=sa.text('0'), nullable=True))

    op.create_table('counters',
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
