"""Add customer_notified_at to packages

Revision ID: 454b2a2c73c5
Revises: 39ce3eb541e4
Create Date: 2026-03-02 20:13:53.720853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454b2a2c73c5'
down_revision = '39ce3eb541e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_notified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('customer_notified_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('customer_notified_by')
        batch_op.drop_column('customer_notified_at')

    # ### end Alembic commands ###
