"""add is_read + updated_by_admin to package_search_cases

Revision ID: 4601fc98406b
Revises: b79987ab43b0
Create Date: 2026-03-03 17:37:28.495516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4601fc98406b'
down_revision = 'b79987ab43b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_search_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_package_search_cases_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_search_cases_updated_by_admin_id'), ['updated_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['updated_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_search_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_package_search_cases_updated_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_package_search_cases_is_read'))
        batch_op.drop_column('updated_by_admin_id')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
