"""add payroll pay frequency

Revision ID: 47e5787f0f23
Revises: d39885a61976
Create Date: 2026-06-08 13:29:05.815789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e5787f0f23'
down_revision = 'd39885a61976'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('employee_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_frequency', sa.String(length=20), nullable=True))

    op.execute("UPDATE employee_payroll SET pay_frequency = 'monthly' WHERE pay_frequency IS NULL")

    with op.batch_alter_table('employee_payroll', schema=None) as batch_op:
        batch_op.alter_column('pay_frequency', nullable=False)
        batch_op.create_index(batch_op.f('ix_employee_payroll_pay_frequency'), ['pay_frequency'], unique=False)

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_frequency', sa.String(length=20), nullable=True))

    op.execute("UPDATE payroll_runs SET pay_frequency = 'monthly' WHERE pay_frequency IS NULL")

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.alter_column('pay_frequency', nullable=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_pay_frequency'), ['pay_frequency'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_pay_frequency'))
        batch_op.drop_column('pay_frequency')

    with op.batch_alter_table('employee_payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_payroll_pay_frequency'))
        batch_op.drop_column('pay_frequency')

    # ### end Alembic commands ###
