"""add sl_name to shipment_log

Revision ID: 567cda9ca6cc
Revises: 4f56cf6ff88c
Create Date: 2026-02-11 11:55:38.125396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567cda9ca6cc'
down_revision = '4f56cf6ff88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.drop_column('sl_name')

    # ### end Alembic commands ###
