"""add shipper to Package

Revision ID: 5c56d887ff76
Revises: c6502b1a9236
Create Date: 2025-11-24 13:59:36.594357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c56d887ff76'
down_revision = 'c6502b1a9236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipper', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('shipper')

    # ### end Alembic commands ###
