"""Link packages to scheduled deliveries

Revision ID: 5ccb114accad
Revises: 0bad31ca9a1a
Create Date: 2025-12-31 00:19:32.489740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccb114accad'
down_revision = '0bad31ca9a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_delivery_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_packages_scheduled_delivery_id'), ['scheduled_delivery_id'], unique=False)
        batch_op.create_foreign_key(None, 'scheduled_deliveries', ['scheduled_delivery_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_status'))

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_packages_scheduled_delivery_id'))
        batch_op.drop_column('scheduled_delivery_id')

    # ### end Alembic commands ###
