"""claims refund issued fields

Revision ID: 5d87c60c79ec
Revises: 2e9792c86907
Create Date: 2026-03-03 00:41:52.752280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d87c60c79ec'
down_revision = '2e9792c86907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_issued', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('refund_issued_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('refund_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('refund_issued_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_issued_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refunded_amount_jmd', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['refund_issued_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('refunded_amount_jmd')
        batch_op.drop_column('refund_issued_by_admin_id')
        batch_op.drop_column('refund_issued_at')
        batch_op.drop_column('refund_reference')
        batch_op.drop_column('refund_issued_method')
        batch_op.drop_column('refund_issued')

    # ### end Alembic commands ###
