"""add freight and customs fields to Settings

Revision ID: 5dca82a7efcf
Revises: 32048c2e1bc4
Create Date: 2025-11-30 01:25:24.934673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dca82a7efcf'
down_revision = '32048c2e1bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_below_1lb_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('per_0_1lb_below_1lb_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('min_billable_weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('per_lb_above_100_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('handling_above_100_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weight_round_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customs_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('customs_exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('gct_25_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gct_15_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('caf_residential_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('caf_commercial_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('diminis_point_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_duty_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('insurance_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('scf_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('envl_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stamp_duty_jmd', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shipment_packages_package'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_shipment_packages_package'), ['package_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('stamp_duty_jmd')
        batch_op.drop_column('envl_rate')
        batch_op.drop_column('scf_rate')
        batch_op.drop_column('insurance_rate')
        batch_op.drop_column('default_duty_rate')
        batch_op.drop_column('diminis_point_usd')
        batch_op.drop_column('caf_commercial_jmd')
        batch_op.drop_column('caf_residential_jmd')
        batch_op.drop_column('gct_15_rate')
        batch_op.drop_column('gct_25_rate')
        batch_op.drop_column('customs_exchange_rate')
        batch_op.drop_column('customs_enabled')
        batch_op.drop_column('weight_round_method')
        batch_op.drop_column('handling_above_100_jmd')
        batch_op.drop_column('per_lb_above_100_jmd')
        batch_op.drop_column('min_billable_weight')
        batch_op.drop_column('per_0_1lb_below_1lb_jmd')
        batch_op.drop_column('special_below_1lb_jmd')

    # ### end Alembic commands ###
