"""add scheduled pickups

Revision ID: 642dddd991e9
Revises: 11d9ddc98297
Create Date: 2026-06-03 10:59:50.091613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642dddd991e9'
down_revision = '11d9ddc98297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('authorized_person', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_pickups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_pickups_pickup_date'), ['pickup_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_pickups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_pickups_user_id'), ['user_id'], unique=False)

    op.create_table('pickup_packages',
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_id'], ['scheduled_pickups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pickup_id', 'package_id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'current_location',
            sa.String(length=50),
            nullable=False,
            server_default='Warehouse'
        ))    
        batch_op.create_index(batch_op.f('ix_packages_current_location'), ['current_location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_current_location'))
        batch_op.drop_column('current_location')

    op.drop_table('pickup_packages')
    with op.batch_alter_table('scheduled_pickups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_pickups_user_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_pickups_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_pickups_pickup_date'))

    op.drop_table('scheduled_pickups')
    # ### end Alembic commands ###
