"""add prealert invoice metadata + link

Revision ID: 670880e31ed1
Revises: 8274d999f34b
Create Date: 2026-02-19 17:39:16.729207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670880e31ed1'
down_revision = '8274d999f34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invoice_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invoice_resource_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('linked_package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prealerts_linked_package_id'), ['linked_package_id'], unique=False)
        batch_op.create_foreign_key(None, 'packages', ['linked_package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prealerts_linked_package_id'))
        batch_op.drop_column('linked_at')
        batch_op.drop_column('linked_package_id')
        batch_op.drop_column('invoice_resource_type')
        batch_op.drop_column('invoice_public_id')
        batch_op.drop_column('invoice_original_name')

    # ### end Alembic commands ###
