"""upgrade scheduled delivery system

Revision ID: 6836b56903bf
Revises: df086922d59b
Create Date: 2026-05-19 10:32:28.506912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6836b56903bf'
down_revision = 'df086922d59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_parish', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_drive_minutes', sa.Integer(), nullable=True))        
        batch_op.add_column(sa.Column('delivery_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('google_place_id', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                'delivery_type',
                sa.String(length=30),
                nullable=False,
                server_default='free_route'
            )
        )

        batch_op.add_column(
            sa.Column(
                'is_free_delivery',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )

        batch_op.add_column(
            sa.Column(
                'delivery_risk_status',
                sa.String(length=20),
                nullable=False,
                server_default='safe'
            )
        )
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_delivery_branch'), ['delivery_branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_delivery_parish'), ['delivery_parish'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_delivery_risk_status'), ['delivery_risk_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_delivery_type'), ['delivery_type'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kingston_dispatch_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stc_dispatch_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kingston_delivery_branch_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stc_delivery_branch_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_base_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_base_fee_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('delivery_per_km_jmd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('google_maps_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kingston_free_delivery_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stc_free_delivery_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_delivery_distance_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('allow_saturday_delivery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('saturday_delivery_fee_jmd', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('saturday_delivery_fee_jmd')
        batch_op.drop_column('allow_saturday_delivery')
        batch_op.drop_column('max_delivery_distance_km')
        batch_op.drop_column('stc_free_delivery_days')
        batch_op.drop_column('kingston_free_delivery_days')
        batch_op.drop_column('google_maps_api_key')
        batch_op.drop_column('delivery_per_km_jmd')
        batch_op.drop_column('delivery_base_fee_jmd')
        batch_op.drop_column('delivery_base_km')
        batch_op.drop_column('stc_delivery_branch_name')
        batch_op.drop_column('kingston_delivery_branch_name')
        batch_op.drop_column('stc_dispatch_address')
        batch_op.drop_column('kingston_dispatch_address')

    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_delivery_type'))
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_delivery_risk_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_delivery_parish'))
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_delivery_branch'))
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('delivery_risk_status')
        batch_op.drop_column('google_place_id')
        batch_op.drop_column('delivery_longitude')
        batch_op.drop_column('delivery_latitude')
        batch_op.drop_column('is_free_delivery')
        batch_op.drop_column('delivery_type')
        batch_op.drop_column('estimated_drive_minutes')
        batch_op.drop_column('distance_km')
        batch_op.drop_column('delivery_branch')
        batch_op.drop_column('delivery_parish')

    # ### end Alembic commands ###
