"""Add package attachments

Revision ID: 6a2ecabf1c53
Revises: 5ccb114accad
Create Date: 2025-12-31 23:14:05.309061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2ecabf1c53'
down_revision = '5ccb114accad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_attachments_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_attachments_package_id'))

    op.drop_table('package_attachments')
    # ### end Alembic commands ###
