"""add subscription members

Revision ID: 71b464018344
Revises: aa28aa38304c
Create Date: 2026-05-01 19:43:14.278664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b464018344'
down_revision = 'aa28aa38304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'user_id', name='uq_subscription_member_user')
    )
    with op.batch_alter_table('subscription_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_members_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_members_subscription_id'))

    op.drop_table('subscription_members')
    # ### end Alembic commands ###
