"""add package link to claims

Revision ID: 71d30ced8fe4
Revises: d8fe480b24e8
Create Date: 2026-03-13 01:59:44.211914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d30ced8fe4'
down_revision = 'd8fe480b24e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_claims_package_id'), ['package_id'], unique=False)
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_claims_package_id'))
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
