"""add pos closeout table

Revision ID: 79b216766cc6
Revises: 8440c98ea99e
Create Date: 2026-04-24 12:32:45.756771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b216766cc6'
down_revision = '8440c98ea99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_closeouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_card', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_transfer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_difference', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_closeouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_closeouts_business_date'), ['business_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_pos_closeouts_closed_by_admin_id'), ['closed_by_admin_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_closeouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_closeouts_closed_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_pos_closeouts_business_date'))

    op.drop_table('pos_closeouts')
    # ### end Alembic commands ###
