"""add payroll tables

Revision ID: 7ef5e369a2e0
Revises: 79b216766cc6
Create Date: 2026-04-24 23:35:37.680667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef5e369a2e0'
down_revision = '79b216766cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.String(length=20), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_items')
    op.drop_table('employee_payroll')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
