"""add nht and education tax to payroll items

Revision ID: 922fbf369d87
Revises: 2bfcac87c55e
Create Date: 2026-04-26 12:24:42.886453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922fbf369d87'
down_revision = '2bfcac87c55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nht', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('education_tax', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.drop_column('education_tax')
        batch_op.drop_column('nht')

    # ### end Alembic commands ###
