"""Add is_enabled to users

Revision ID: 926404325f48
Revises: 22f4a93318f9
Create Date: 2026-02-14 23:15:14.379124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926404325f48'
down_revision = '22f4a93318f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
