"""Add shipment archive fields and logs

Revision ID: 943b7d319ceb
Revises: 4601fc98406b
Create Date: 2026-03-05 01:04:02.652402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '943b7d319ceb'
down_revision = '4601fc98406b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_archive_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_archive_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_archive_logs_actor_admin_id'), ['actor_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_archive_logs_shipment_id'), ['shipment_id'], unique=False)

    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archived_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('unarchive_override_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_shipment_log_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_log_archived_by_admin_id'), ['archived_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_log_unarchive_override_until'), ['unarchive_override_until'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['archived_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shipment_log_unarchive_override_until'))
        batch_op.drop_index(batch_op.f('ix_shipment_log_archived_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_log_archived_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('unarchive_override_until')
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_by_admin_id')
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('shipment_archive_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_archive_logs_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_archive_logs_actor_admin_id'))

    op.drop_table('shipment_archive_logs')
    # ### end Alembic commands ###
