"""add claim case_id

Revision ID: 94787b17c1fd
Revises: 5d87c60c79ec
Create Date: 2026-03-03 02:20:15.592295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94787b17c1fd'
down_revision = '5d87c60c79ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_claims_case_id'), ['case_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_case_id'))
        batch_op.drop_column('case_id')

    # ### end Alembic commands ###
