"""Add pay advance to payroll items

Revision ID: 9479fbb6bc07
Revises: 3ec6a087d97e
Create Date: 2026-06-12 15:56:13.458935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9479fbb6bc07'
down_revision = '3ec6a087d97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_advance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.drop_column('pay_advance')

    # ### end Alembic commands ###
