"""Add user updated_at timestamps

Revision ID: 98d0577ffc95
Revises: 6a2ecabf1c53
Create Date: 2026-01-07 10:46:43.435079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d0577ffc95'
down_revision = '6a2ecabf1c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at_dt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at_dt')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
