"""Add subscription waiver fields

Revision ID: 9b7e10d43504
Revises: 3a9111600383
Create Date: 2026-05-24 19:28:36.464005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7e10d43504'
down_revision = '3a9111600383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_waived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('waiver_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('waived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('waived_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['waived_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('waived_by_admin_id')
        batch_op.drop_column('waived_at')
        batch_op.drop_column('waiver_reason')
        batch_op.drop_column('is_admin_waived')

    # ### end Alembic commands ###
