"""add package_search_cases

Revision ID: b79987ab43b0
Revises: a21bdc7a7590
Create Date: 2026-03-03 07:23:34.048617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79987ab43b0'
down_revision = 'a21bdc7a7590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_search_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=128), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=False),
    sa.Column('proof_url', sa.Text(), nullable=False),
    sa.Column('proof_public_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_search_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_search_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_package_search_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_search_cases_tracking_number'), ['tracking_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_search_cases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_search_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_search_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_package_search_cases_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_package_search_cases_status'))
        batch_op.drop_index(batch_op.f('ix_package_search_cases_case_id'))

    op.drop_table('package_search_cases')
    # ### end Alembic commands ###
