"""Add prealert attachments

Revision ID: b9d485312db5
Revises: f790e2f00ad3
Create Date: 2026-06-27 12:37:30.713832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d485312db5'
down_revision = 'f790e2f00ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prealert_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prealert_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('cloud_public_id', sa.String(length=255), nullable=True),
    sa.Column('cloud_resource_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prealert_id'], ['prealerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prealert_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prealert_attachments_prealert_id'), ['prealert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealert_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prealert_attachments_prealert_id'))

    op.drop_table('prealert_attachments')
    # ### end Alembic commands ###
