"""Add subscription billable weight to packages

Revision ID: c2351a947dad
Revises: b9d485312db5
Create Date: 2026-07-21 09:57:42.175898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2351a947dad'
down_revision = 'b9d485312db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_billable_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('subscription_billable_weight')

    # ### end Alembic commands ###
