"""Add manual lock fields to prealerts

Revision ID: c2f6a80b549f
Revises: 9479fbb6bc07
Create Date: 2026-06-18 12:26:07.233713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f6a80b549f'
down_revision = '9479fbb6bc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lock_reason', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_prealerts_is_locked'), ['is_locked'], unique=False)
        batch_op.create_index(batch_op.f('ix_prealerts_locked_by_admin_id'), ['locked_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['locked_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prealerts_locked_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_prealerts_is_locked'))
        batch_op.drop_column('lock_reason')
        batch_op.drop_column('locked_by_admin_id')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
