"""add registration settings

Revision ID: c7ed577d13a7
Revises: 334fa608c9a5
Create Date: 2026-05-06 06:47:11.627508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ed577d13a7'
down_revision = '334fa608c9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_prefix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_number_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reuse_deleted_registration_numbers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lock_registration_number', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('lock_registration_number')
        batch_op.drop_column('reuse_deleted_registration_numbers')
        batch_op.drop_column('registration_number_width')
        batch_op.drop_column('registration_prefix')

    # ### end Alembic commands ###
