"""Add delivery time range

Revision ID: cb229572eb0c
Revises: 2dfa79ef7e0d
Create Date: 2026-02-23 22:28:32.967663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb229572eb0c'
down_revision = '2dfa79ef7e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time_to', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time_to')
        batch_op.drop_column('scheduled_time_from')

    # ### end Alembic commands ###
