"""add payroll allowance deduction fields

Revision ID: d08725f5cd94
Revises: dad639d3ef6e
Create Date: 2026-04-25 03:18:50.438287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08725f5cd94'
down_revision = 'dad639d3ef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('overtime', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nis', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_items', schema=None) as batch_op:
        batch_op.drop_column('other_deductions')
        batch_op.drop_column('tax')
        batch_op.drop_column('nis')
        batch_op.drop_column('bonus')
        batch_op.drop_column('overtime')
        batch_op.drop_column('allowance')

    # ### end Alembic commands ###
