"""add audit log reason

Revision ID: d39885a61976
Revises: 2b05630321e6
Create Date: 2026-06-08 00:15:23.303079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39885a61976'
down_revision = '2b05630321e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_reason'), ['reason'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_reason'))
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
