"""Add expense attachments and expense audit logs

Revision ID: d6acecdfd804
Revises: f0541b2b1e7c
Create Date: 2026-01-09 02:05:13.975546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6acecdfd804'
down_revision = 'f0541b2b1e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('expense_category', sa.String(length=120), nullable=True),
    sa.Column('expense_amount', sa.Float(), nullable=True),
    sa.Column('expense_description', sa.Text(), nullable=True),
    sa.Column('expense_attachment_name', sa.String(length=255), nullable=True),
    sa.Column('expense_attachment_stored', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_audit_logs_expense_id'), ['expense_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_stored', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_mime', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('attachment_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('attachment_uploaded_at')
        batch_op.drop_column('attachment_mime')
        batch_op.drop_column('attachment_stored')
        batch_op.drop_column('attachment_name')

    with op.batch_alter_table('expense_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_audit_logs_expense_id'))

    op.drop_table('expense_audit_logs')
    # ### end Alembic commands ###
