"""add payment transaction system

Revision ID: d8fe480b24e8
Revises: 73799bd1d0d0
Create Date: 2026-03-11 14:34:27.056056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fe480b24e8'
down_revision = '73799bd1d0d0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorized_by_admin_id', sa.Integer(), nullable=True))

        batch_op.add_column(
            sa.Column('source', sa.String(length=30), nullable=False, server_default='admin')
        )
        batch_op.add_column(sa.Column('scheduled_delivery_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claim_id', sa.Integer(), nullable=True))

        batch_op.add_column(
            sa.Column('transaction_type', sa.String(length=30), nullable=False, server_default='invoice_payment')
        )
        batch_op.add_column(
            sa.Column('status', sa.String(length=20), nullable=False, server_default='completed')
        )

        batch_op.alter_column(
            'invoice_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )

        batch_op.create_index(batch_op.f('ix_payments_authorized_by_admin_id'), ['authorized_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_scheduled_delivery_id'), ['scheduled_delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])
        batch_op.create_foreign_key(None, 'claims', ['claim_id'], ['id'])
        batch_op.create_foreign_key(None, 'scheduled_deliveries', ['scheduled_delivery_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['authorized_by_admin_id'], ['id'])

    # optional cleanup: remove server defaults after backfill
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('source', server_default=None)
        batch_op.alter_column('transaction_type', server_default=None)
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_source'))
        batch_op.drop_index(batch_op.f('ix_payments_scheduled_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_payments_package_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_claim_id'))
        batch_op.drop_index(batch_op.f('ix_payments_authorized_by_admin_id'))
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('claim_id')
        batch_op.drop_column('package_id')
        batch_op.drop_column('scheduled_delivery_id')
        batch_op.drop_column('source')
        batch_op.drop_column('authorized_by_admin_id')

    # ### end Alembic commands ###
