"""add payroll paid tracking

Revision ID: dad639d3ef6e
Revises: 7ef5e369a2e0
Create Date: 2026-04-25 02:33:21.385607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad639d3ef6e'
down_revision = '7ef5e369a2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('paid_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['paid_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paid_by_admin_id')
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
