"""Add broadcast fields to notifications

Revision ID: dbf339644ffa
Revises: 3e9a6ea45a26
Create Date: 2026-01-08 10:59:32.272438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbf339644ffa'
down_revision = '3e9a6ea45a26'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add is_broadcast safely (server_default so existing rows get a value)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_broadcast', sa.Boolean(), nullable=False, server_default=sa.text('false'))
        )

    # 2) Backfill any NULLs that may exist (extra safety)
    op.execute("UPDATE notifications SET is_broadcast = false WHERE is_broadcast IS NULL;")
    op.execute("UPDATE notifications SET is_read = false WHERE is_read IS NULL;")
    op.execute("UPDATE notifications SET created_at = NOW() WHERE created_at IS NULL;")

    # 3) Now enforce NOT NULL + indexes + timezone conversion
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('false')
        )

        # Convert created_at to timezone-aware + NOT NULL
        # NOTE: existing_type postgres.TIMESTAMP() means "timestamp without time zone"
        batch_op.alter_column('created_at',
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            nullable=False
        )

        batch_op.create_index(batch_op.f('ix_notifications_is_broadcast'), ['is_broadcast'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    # 4) Optional: remove server defaults (keeps schema clean; ORM defaults still apply)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_broadcast', server_default=None)
        batch_op.alter_column('is_read', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_broadcast'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('is_broadcast')

    # ### end Alembic commands ###
