"""add subscription reminder tracking fields

Revision ID: df086922d59b
Revises: c7ed577d13a7
Create Date: 2026-05-14 10:52:36.403886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df086922d59b'
down_revision = 'c7ed577d13a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_reminder_5d_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('renewal_reminder_2d_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expiry_notice_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('expiry_notice_sent')
        batch_op.drop_column('renewal_reminder_2d_sent')
        batch_op.drop_column('renewal_reminder_5d_sent')

    # ### end Alembic commands ###
