"""add supplier payment reference to expected collections

Revision ID: e4b112426638
Revises: de89b5f955ee
Create Date: 2026-08-05 23:15:48.251504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b112426638'
down_revision = 'de89b5f955ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_expected_package_collections_payment_reference'), ['payment_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_package_collections_payment_reference'))
        batch_op.drop_column('payment_reference')

    # ### end Alembic commands ###
