"""prealert link fields timezone + relationship

Revision ID: e66cadf014c2
Revises: 670880e31ed1
Create Date: 2026-02-20 10:46:33.609255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e66cadf014c2'
down_revision = '670880e31ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.alter_column('linked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.alter_column('linked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
