"""Add service charge to expected package collections

Revision ID: ea3f996b1a36
Revises: e4b112426638
Create Date: 2026-08-31 08:49:11.135174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3f996b1a36'
down_revision = 'e4b112426638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_charge_jmd', sa.Numeric(precision=14, scale=2), server_default='5000.00', nullable=False))
        batch_op.add_column(sa.Column('has_invoice_over_100', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.drop_column('has_invoice_over_100')
        batch_op.drop_column('service_charge_jmd')

    # ### end Alembic commands ###
