"""add expected package collections

Revision ID: ea4d5a84081c
Revises: 570337e2011b
Create Date: 2026-08-05 07:57:42.483727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4d5a84081c'
down_revision = '570337e2011b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_package_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_number', sa.String(length=40), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=160), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('total_weight_lbs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_rate_usd_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_band_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_total_jmd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_total_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_total_jmd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculation_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_package_collections_collection_number'), ['collection_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_expected_package_collections_shipment_id'), ['shipment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_expected_package_collections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expected_package_collections_supplier_invoice_number'), ['supplier_invoice_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_package_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_package_collections_supplier_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_expected_package_collections_status'))
        batch_op.drop_index(batch_op.f('ix_expected_package_collections_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_expected_package_collections_collection_number'))

    op.drop_table('expected_package_collections')
    # ### end Alembic commands ###
