"""add wallet audit fields

Revision ID: ead6cb238261
Revises: 642dddd991e9
Create Date: 2026-06-06 10:33:05.469427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead6cb238261'
down_revision = '642dddd991e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wallet_transactions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_reason'), ['reason'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_reason'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_package_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_admin_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_action'))
        batch_op.drop_column('admin_id')
        batch_op.drop_column('package_id')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('reason')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
