"""add US warehouse address fields to Settings

Revision ID: ed143fd76a7c
Revises: 616cea7e6410
Create Date: 2025-11-18 09:01:04.517323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed143fd76a7c'
down_revision = '616cea7e6410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_invoices')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_column('total')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('received_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_packages_created_at'))
        batch_op.drop_index(batch_op.f('ix_packages_epc'))
        batch_op.drop_index(batch_op.f('ix_packages_status'))
        batch_op.drop_column('category')
        batch_op.drop_column('other_charges')
        batch_op.drop_column('stamp')
        batch_op.drop_column('freight_total')
        batch_op.drop_column('envl')
        batch_op.drop_column('shipper')
        batch_op.drop_column('storage_fee')
        batch_op.drop_column('customs_total')
        batch_op.drop_column('caf')
        batch_op.drop_column('epc')
        batch_op.drop_column('grand_total')
        batch_op.drop_column('scf')
        batch_op.drop_column('freight_fee')
        batch_op.drop_column('gct')
        batch_op.drop_column('duty')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    with op.batch_alter_table('pending_referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_pending_referrals_created_at'))
        batch_op.drop_index(batch_op.f('ix_pending_referrals_referred_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_pending_referrals_referred_user_id_users'), type_='foreignkey')
        batch_op.drop_column('referred_user_id')
        batch_op.drop_column('bonus_amount')

    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_prealerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_prealerts_prealert_number'))
        batch_op.drop_index(batch_op.f('ix_prealerts_user_id'))
        batch_op.create_index(batch_op.f('ix_prealerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_prealerts_customer_id_users', 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('rate_brackets', schema=None) as batch_op:
        batch_op.alter_column('max_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('ux_rate_brackets_max_weight'), type_='unique')
        batch_op.create_index(batch_op.f('ix_rate_brackets_max_weight'), ['max_weight'], unique=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_deliveries_created_at'))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('us_street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('us_suite_prefix', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('us_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('us_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('us_zip', sa.String(length=20), nullable=True))
        batch_op.alter_column('company_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('currency_symbol',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('usd_to_jmd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('base_rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('handling_fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_log_created_at'))

    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('date_registered',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_constraint(batch_op.f('fk_users_referrer_id_users'), type_='foreignkey')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('active')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_referrer_id_users'), 'users', ['referrer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.alter_column('date_registered',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               nullable=True)

    with op.batch_alter_table('shipment_packages', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('shipment_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('handling_fee',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('base_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('usd_to_jmd',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
        batch_op.alter_column('currency_symbol',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('company_address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('us_zip')
        batch_op.drop_column('us_state')
        batch_op.drop_column('us_city')
        batch_op.drop_column('us_suite_prefix')
        batch_op.drop_column('us_street')

    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_deliveries_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('rate_brackets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rate_brackets_max_weight'))
        batch_op.create_unique_constraint(batch_op.f('ux_rate_brackets_max_weight'), ['max_weight'])
        batch_op.alter_column('rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('max_weight',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('prealerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prealerts_customer_id'))
        batch_op.create_index(batch_op.f('ix_prealerts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prealerts_prealert_number'), ['prealert_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_prealerts_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('purchase_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('pending_referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('referred_user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_pending_referrals_referred_user_id_users'), 'users', ['referred_user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_pending_referrals_referred_user_id'), ['referred_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_referrals_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('accepted')
        batch_op.drop_column('referred_email')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duty', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('freight_fee', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('scf', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('grand_total', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('epc', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('caf', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('customs_total', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('storage_fee', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('shipper', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('envl', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('freight_total', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('stamp', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('other_charges', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_packages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_epc'), ['epc'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('received_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('_alembic_tmp_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('total_weight', sa.FLOAT(), nullable=True),
    sa.Column('invoice_value', sa.FLOAT(), nullable=True),
    sa.Column('duty', sa.FLOAT(), nullable=True),
    sa.Column('scf', sa.FLOAT(), nullable=True),
    sa.Column('envl', sa.FLOAT(), nullable=True),
    sa.Column('caf', sa.FLOAT(), nullable=True),
    sa.Column('gct', sa.FLOAT(), nullable=True),
    sa.Column('handling', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('date_submitted', sa.DATETIME(), nullable=True),
    sa.Column('date_paid', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('amount_due', sa.FLOAT(), nullable=True),
    sa.Column('grand_total', sa.FLOAT(), nullable=True),
    sa.Column('date_issued', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
