"""add purchase request items

Revision ID: f790e2f00ad3
Revises: f2c81874e80f
Create Date: 2026-06-22 12:07:05.307934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f790e2f00ad3'
down_revision = 'f2c81874e80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('item_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quoted_item_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_request_items_purchase_request_id'), ['purchase_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_request_items_purchase_request_id'))

    op.drop_table('purchase_request_items')
    # ### end Alembic commands ###
