"""add delivered timestamp

Revision ID: ffc62e2dc629
Revises: 6836b56903bf
Create Date: 2026-05-21 01:15:09.414064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc62e2dc629'
down_revision = '6836b56903bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_deliveries', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
